## Introduction

## Methods

In [15]:
from osgeo import gdal
import sys
import numpy as np

src_ds = gdal.Open( "images/Ky1Can.tif" )

print ("[ RASTER BAND COUNT ]: ", src_ds.RasterCount)
for band in range( src_ds.RasterCount ):
    band += 1
    print ("[ GETTING BAND ]: ", band)
    srcband = src_ds.GetRasterBand(band)

    stats = srcband.GetStatistics( True, True )

    print ("[ STATS ] =  Minimum=%.3f, Maximum=%.3f, Mean=%.3f, StdDev=%.3f" % ( \
            stats[0], stats[1], stats[2], stats[3] ))

    rast_array = np.array(src_ds.GetRasterBand(1).ReadAsArray())
    print (rast_array)

[ RASTER BAND COUNT ]:  1
[ GETTING BAND ]:  1
[ STATS ] =  Minimum=0.000, Maximum=254.000, Mean=45.543, StdDev=40.225
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


AttributeError: 'NoneType' object has no attribute 'RasterCount'